# Generated by Django 5.2.6 on 2025-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("course", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
            ],
        ),
    ]
